const propiedades = [
  {
    id: 1,
    tipo: 'Casa',
    precio: 160000,
    ubicación: "centro",
    titulo: 'Casa de con 3  dormitorios habitaciones y con patio',
    habitaciones: 3,
    baños: 2,
    patio: "Si",
    img: "../IMG/portada.jpeg",

  },
  {
    id: 2,
    tipo: 'Departamento',
    precio: 160000,
    ubicación: "centro",
    titulo: 'Departamento de con cuatro 4 habitaciones 2 baños y con patio',
    habitaciones: 4,
    baños: 1,
    patio: "No",
    img: "../IMG/portada.jpeg",

  },
  {
    id: 3,
    tipo: 'Casa',
    precio: 160000,
    ubicación: "centro",
    titulo: 'Casa  de con  tres 3 habitaciones cocina, comedor y con patio',
    habitaciones: 5,
    baños: 2,
    patio: "Si",
    img: "../IMG/portada.jpeg",

  },
  {
    id: 4,
    tipo: 'Departamento',
    precio: 160000,
    ubicación: "centro",
    titulo: 'Departamento con un de una 1  dormitorio habitacion  con y estacionamiento',
    habitaciones: 1,
    baños: 1,
    patio: "No",
    img: "../IMG/portada.jpeg",
  },
  {
    id: 5,
    tipo: 'Casa',
    precio: 160000,
    ubicación: "centro",
    titulo: 'Casa con de tres 3 dormitorios habitaciones y con patio',
    habitaciones: 3,
    baños: 2,
    patio: "Si",
    img: "../IMG/portada.jpeg",
  },
  {
    id: 6,
    tipo: 'Departamento',
    precio: 160000,
    ubicación: "centro",
    titulo: 'Departamento con de tres 3 dormitorios habitaciones y con estacionamiento',
    habitaciones: 3,
    baños: 1,
    patio: "No",
    img: "../IMG/portada.jpeg",

  },
  {
    id: 7,
    tipo: 'Casa',
    precio: 160000,
    ubicacion: "centro",
    titulo: 'Casa con de tres 3  dormitorios habitaciones y con patio',
    habitaciones: 3,
    baños: 2,
    patio: "Si",
    img: "../IMG/portada.jpeg",

  },
  {
    id: 8,
    tipo: 'Departamento',
    precio: 160000,
    ubicación: "centro",
    titulo: 'Departamento de cuatro con  4 habitaciones dormitorios y con estacionamiento',
    habitaciones: 4,
    baños: 1,
    patio: "No",
    img: "../IMG/portada.jpeg",
  },
  {
    id: 9,
    tipo: 'Casa',
    precio: 11111110000,
    ubicación: "centro",
    titulo: 'Casa de con  tres 3 dormitorios habitaciones y con patio',
    habitaciones: 5,
    baños: 2,
    patio: "Si",
    img: "../IMG/portada.jpeg",

  },
  {
    id: 10,
    tipo: 'Departamento',
    precio: 120000,
    ubicación: "centro",
    titulo: 'Departamento con de una   1 una un dormitorio habitaciones y con patio',
    habitaciones: 1,
    baños: 1,
    patio: "No",
    img: "../IMG/portada.jpeg",

  },
  {
    id: 11,
    tipo: 'Departamento',
    precio: 120000,
    ubicación: "centro",
    titulo: 'Departamento con una 1 un  dormitorio habitaciones y patio',
    habitaciones: 1,
    baños: 1,
    patio: "No",
    img: "../IMG/portada.jpeg",

  },

]

export default propiedades;