const propiedades = [
    {
        id: 1,
        tipo: 'Casa',
        precio: 160000,
        ubicacion: "centro",
        titulo: 'Casa con cocina/comedor y 3 habitaciones',
        habitaciones: 3,
        baños: 2,
        patio: true,
        img: "./IMG/portada.jpeg",

    },
    {
        id: 2,
        tipo: 'Departamento',
        precio: 160000,
        ubicacion: "centro",
        titulo: 'Departamento con cocina comedor y 4 habitaciones',
        habitaciones: 4,
        baños: 1,
        patio: false,
        img: "./IMG/portada.jpeg",

    },
    {
        id: 3,
        tipo: 'Casa',
        precio: 160000,
        ubicacion: "centro",
        titulo: 'Casa con cocina/comedor y 3 habitaciones',
        habitaciones: 5,
        baños: 2,
        patio: true,
        img: "./IMG/portada.jpeg",

      },
      {
        id: 4,
        tipo: 'Departamento',
        precio: 160000,
        ubicacion: "centro",
        titulo: 'Departamento con cocina, comedor y 1habitaciones',
        habitaciones: 1,
        baños: 1,
        patio: false,
        img: "./IMG/portada.jpeg",
      },
      {
        id: 5,
        tipo: 'Casa',
        precio: 160000,
        ubicacion: "centro",
        titulo: 'Casa con cocina/comedor y 3 habitaciones',
        habitaciones: 3,
        baños: 2,
        patio: true,
        img: "./IMG/portada.jpeg",

      },
      {
        id: 6,
        tipo: 'Departamento',
        precio: 160000,
        ubicacion: "centro",
        titulo: 'Departamento con cocina, comedor y 3 habitaciones',
        habitaciones: 3,
        baños: 1,
        patio: false,
        img: "./IMG/portada.jpeg",

      },
      {
        id: 7,
        tipo: 'Casa',
        precio: 160000,
        ubicacion: "centro",
        titulo: 'Casa con cocina/comedor y 3 habitaciones',
        habitaciones: 3,
        baños: 2,
        patio: true,
        img: "./IMG/portada.jpeg",

    },
    {
        id: 8,
        tipo: 'Departamento',
        precio: 160000,
        ubicacion: "centro",
        titulo: 'Departamento con cocina comedor y 4 habitaciones',
        habitaciones: 4,
        baños: 1,
        patio: false,
        img: "./IMG/portada.jpeg",
    },
    {
        id: 9,
        tipo: 'Casa',
        precio: 160000,
        ubicacion: "centro",
        titulo: 'Casa con cocina/comedor y 3 habitaciones',
        habitaciones: 5,
        baños: 2,
        patio: true,
        img: "./IMG/portada.jpeg",
        
      },
      {
        id: 10,
        tipo: 'Departamento',
        precio: 120000,
        ubicacion: "centro",
        titulo: 'Departamento con cocina, comedor y 1habitaciones',
        habitaciones: 1,
        baños: 1,
        patio: false,
        img: "./IMG/portada.jpeg",

      },
     
]

export default propiedades;